shotstack/shotstack-forms

- src/routes/default.json
Default JSON needs to have at least one merge field to show and demonstrate appropriate working behaviour
> Feat: Updating default.json to have at least one merge field

- .gitignore
- src/ShotstackEditTemplate/ShotstackEditTemplateService.test.ts
- src/ShotstackEditTemplate/ShotstackEditTemplateService.ts
- src/ShotstackEditTemplate/constants.ts
- src/ShotstackEditTemplate/types.ts
- src/ShotstackEditTemplate/validate.test.ts
- src/ShotstackEditTemplate/validate.ts
- src/routes/+page.svelte
- Validates an input and returns a verified merge schema (hard coded, pending schema)
- Adds tests for validation method and use cases
- Adding separation of concerns when handling inputs, split into validation and state setting
- Adds constants for error messages for testing and avoiding magic strings
Unit test
e2e test
> Template validation and unit tests

- cypress/e2e/exists.cy.ts
- src/ShotstackEditTemplate/validate.ts
- src/routes/+page.svelte
- Checks that you we dont suffer data loss in the resulting json when pasting a template or modifying the form fields.
- Adds a safeApply function to the default value of the input component
- Small modification to prop existence validation: Removed boolean casting, using the IN operator instead.
e2e:
Jest
> Additional e2e testing

- src/ShotstackEditTemplate/ShotstackEditTemplateService.test.ts
- src/ShotstackEditTemplate/ShotstackEditTemplateService.ts
- src/ShotstackEditTemplate/validate.test.ts
- src/ShotstackEditTemplate/validate.ts
As requested, the find and replace values on a merge field should always be a string, independent of the value it receives. A new function validateMerge is added to ensure that the validation of provided templates follow this rule.
> Validate merge

- jest.config.ts
- package-lock.json
- package.json
- src/lib/ShotstackEditTemplate/validate.test.ts
- src/lib/ShotstackEditTemplate/validate.ts
- src/lib/__snapshots__/index.test.ts.snap
- src/lib/components/Form/Form.css
- src/lib/components/Form/Form.svelte
- src/lib/index.test.ts
- src/routes/+page.svelte
- Needed a tool to test that the entry point of the module was being rendered properly.
- Adds svelte-testing-library to snapshot test the resulting render, and jester-svelte to properly process svelte files.
- Updates configuration files to follow the previously mentioned testing pipeline
jest: 
e2e:
> Feat: Adding svelte testing library to test rendered DOM elements

- .husky/pre-commit
Small update to Husky pre-commit hook, so that it runs the development server before running the cypress e2e tests.
e2e
jest
> Feat: now runs dev server before running cypress

- src/lib/ShotstackEditTemplate/ShotstackEditTemplateService.ts
- src/lib/__snapshots__/index.test.ts.snap
- src/lib/components/Form/Form.svelte
- src/lib/index.test.ts
- src/lib/index.ts
- According to required specifications, library's default export should be initialized with the 'new' keyword, with up to two optional parameters, a json template and the container where the form will be rendered.
- Now validates initial template
- Adding snapshot test for merge rendering on initialization when an element with id shotstack-form-field
- Updated snapshot test
e2e
jest
> Refactor: implementing a class as the default export of the library

- custom.d.ts
- src/lib/ShotstackEditTemplate/ShotstackEditTemplateService.ts
- src/lib/ShotstackEditTemplate/types.ts
- src/lib/index.test.ts
- src/lib/index.ts
- tsconfig.json
- Complies with the required Shotstack.on('event', callback) class method, accord to specifications.
- Adds tests for Shotstack.on
- In order to mock jest functions, additional configurations were required for tsconfig.json, including a module for SVG files.
Cypress e2e:
Jest:
> Feat: Adding events, handlers and related methods to Shotstack class

- README.md
- src/lib/ShotstackEditTemplate/ShotstackEditTemplateService.test.ts
- src/lib/ShotstackEditTemplate/ShotstackEditTemplateService.ts
- src/lib/public/README.md
- Replaces result property with setter and getter to have a better control on the onChange lifecycle, by triggering every change handler when setting the new property and ensuring they work with a valid json template.
- Adds tests for this new functionality
#Test evidence
e2e:
jest:
> Refactor: replaced result with getter+setter

- src/lib/__snapshots__/index.test.ts.snap
- src/lib/components/Form/Form.svelte
- Since #18, form input fields are typecasted into strings, and will no longer throw any kind of errors. As such, there's no need to safe apply input values, and in any error, they will be typecasted into strings anyway.
- Removed safeapply function
- Removed merge fields input error (misnamed as resultError)
- Renamed template error as Error to show only one error field
- Updated snapshots
e2e: 
jest:
> Refactor: form error handling and display

- src/lib/ShotstackEditTemplate/ShotstackEditTemplateService.test.ts
- src/lib/ShotstackEditTemplate/ShotstackEditTemplateService.ts
- src/lib/ShotstackEditTemplate/constants.ts
- src/lib/ShotstackEditTemplate/validate.ts
- src/lib/components/Form/Form.svelte
Expected behaviour:
- When calling Shotstack as a constructor, e.g ```new Shotstack(template)```,  if the initial template had any kind of error, the form should reflect that by rendering an error field and message.
Actual behaviour before this PR:
- When Shotstack was called as a constructor, the form would render normally with default data, with no error message whatsoever.
- Related PR's
#32 
#34 
#37 
- Updating form component's by making its only responsability to organize and render data incoming from EditTemplate component.
- Updating EditTemplate component by incorporating responsabilities previously held by form component, particularly error handling and validating on mount
- Submit method will throw an error and will not run submit handlers if service current error property is …
> Feat: removed all business logic from form component. Reworked error handling.

- src/lib/ShotstackEditTemplate/ShotstackEditTemplateService.test.ts
- src/lib/ShotstackEditTemplate/ShotstackEditTemplateService.ts
- src/lib/ShotstackEditTemplate/types.ts
- src/lib/index.test.ts
- 'change' and 'error' events now provide two parameters to every callback function in the handler array, the first argument being the new set state and the second parameter is the previous state.
- Adds unit tests for all three events
jest
e2e
> Feat: events derived from component state are provided with current state and previous state

- custom.d.ts
- cypress.config.ts
- cypress/e2e/exists.cy.ts
- src/lib/ShotstackEditTemplate/constants.ts
- src/lib/ShotstackEditTemplate/validate.test.ts
- src/lib/ShotstackEditTemplate/validate.ts
- Test coverage for validation helper functions was too low for current standards. Improved it to 100% statement and branch coverage.
- Replaced all 'any' types for unknowns or objects according to the case, and refactored template validation typing and casting.
jest:
e2e:
> Feat: adding tests for validation helper functions and cleared lint warnings

- cypress/e2e/exists.cy.ts
- src/lib/__snapshots__/index.test.ts.snap
- src/lib/components/Form/Form.svelte
- Removes "{{" and "}}" from form component 'find' field name
- Updates snapshots
e2e:
jest:
> UI update: removing handlebars from field name

- src/lib/components/Form/fields/Add.svelte
- Current implementation was not properly clearing out the fields on click
- Replaced svelte variable with stores. Now the clear function updates stores by calling set with an empty string.
> Bugfix: clear on focus now correctly updates field value

- src/lib/ShotstackEditTemplate/ShotstackEditTemplateService.ts
- src/lib/components/Form/Form.svelte
- src/lib/components/Form/fields/Fields.svelte
- Instead of searching for the same find prop, if a reference is provided, it will search by reference.
- If a reference is not provided, will search for the first element where the find property is equal to the find property of the updated field.
- This allows to modify find properties in the future and prevent unwanted effects.
> Refactor: updateResultMergeFields now updates by reference

- README.md
- src/lib/__snapshots__/index.test.ts.snap
- src/lib/index.test.ts
- src/lib/index.ts
- src/lib/public/README.md
- Implements a renderElements(container,after?) method, which renders the inputs from the source template into target container, or after target element if provided.
- Adds unit tests for renderElements and renderForm
- Updates Readme's to reflect latest changes
- Updates snapshots
> Feat: adds renderElements method to main class

- README.md
- src/lib/public/README.md
- Updates Readme with examples on how to extend a custom form and using the renderElements method within.
> Readme: adds more information on usage of renderElements method

- svelte.config.js
- Due to gh-pages url change, styles werent being properly downloaded
- This fix updates the css url to the latest one
> Bugfix: changed gh-pages url to latest one

- src/lib/ShotstackEditTemplate/ShotstackEditTemplateService.ts
- src/lib/ShotstackEditTemplate/types.ts
- Adds a upload event that triggers whenever there's an update on an asset
- Upload callbacks should return a string, the last of which is assigned to the asset and updates its corresponding value.
- This update also triggers change events
> Feat: implements upload event for when a src variable is updated

- src/lib/ShotstackEditTemplate/ShotstackEditTemplateService.test.ts
- src/lib/ShotstackEditTemplate/ShotstackEditTemplateService.ts
- src/lib/ShotstackEditTemplate/types.ts
- Updated typing according to shotstack schema, now following complete type dependency from timeline to asset
- Updated upload callback specifications: now is provided a filelist and must return a string to update the template
> Bugfix: upload callback function now receives a filelist. Updates types

- src/lib/ShotstackEditTemplate/ShotstackEditTemplateService.ts
- src/lib/ShotstackEditTemplate/types.ts
- src/lib/__snapshots__/index.test.ts.snap
- src/lib/components/Form/Form.svelte
- src/lib/components/Form/defaultMerge.json
- src/lib/components/Form/source/Source.svelte
- src/lib/components/Form/source/SourceFields.svelte
- src/lib/index.ts
- Creates Sourcefield component, which accumulates a Source component for every property with placeholder variables in the source template.
- Sourcefield hides when there's no src property with a placeholder value
- Updates default json in order to demo the new elements
- Updates getInputs (and therefore renderElements) to return a collection of Text Input and Labels for every merge field, and a collection of file inputs, text inputs, and labels for every src property with placeholders
- upload callback now accepts a Promise that resolves into a string, which is used to update the source value and the resulting template.
- Updates snapshots
> Feat: implements sourcefields component

- README.md
- src/lib/public/README.md
- Updates main readme and package's readme with upload event information and current behaviour of the renderElements and getInputs methods, which now return a mix of a) Inputs and labels for each merge field, and b) inputs and labels for every src asset with a placeholder value with the following structure: {{ VALUE }}
- Provides a helpful guide on how to implement upload events
> Updates readme with latest upload event information and render methods

- src/lib/ShotstackEditTemplate/ShotstackEditTemplateService.ts
- src/lib/ShotstackEditTemplate/types.ts
- src/lib/components/Form/source/Source.test.ts
- src/lib/components/Form/source/SourceFields.svelte
- src/lib/components/Form/source/SourceFields.test.ts
- src/lib/components/Form/source/utils.test.ts
- src/lib/components/Form/source/utils.ts
- Adds Placeholder type for elements that contain placeholder values and corresponding assets
- Refactors getSrcPlaceholder, to implement Placeholder type and placeholder validation
- Adds component testing for SourceField.svelte and related functions
> Test: adds component testing for SourceField component

- cypress/e2e/exists.cy.ts
- src/lib/__snapshots__/index.test.ts.snap
- src/lib/components/Form/Form.svelte
- src/lib/components/Form/common/helpers.ts
- src/lib/components/Form/result/Icon.svelte
- src/lib/components/Form/result/Json.svelte
- src/lib/components/Form/result/Result.svelte
- src/lib/components/Form/result/Subtitle.svelte
- src/lib/components/Form/result/utils.ts
- src/lib/components/Form/submit/ButtonDownload.test.ts
- src/lib/components/Form/submit/ButtonSubmit.test.ts
- src/lib/components/Form/submit/SubmitArea.test.ts
- src/lib/components/Form/template/Subtitle.svelte
- src/lib/components/Form/template/Template.svelte
- src/lib/components/Form/template/TextArea.svelte
- Split submit section, input template section and result section into different components for testing and compartmentalization purposes.
> Refactor: split Form.svelte into subcomponents

- src/lib/__snapshots__/index.test.ts.snap
- src/lib/components/Form/error/ErrorField.svelte
- src/lib/components/Form/error/ErrorField.test.ts
- src/lib/components/Form/error/Reset.test.ts
-  Adds component testing for Reset.svelte.
-  Adds component testing for ErrorField.svelte.
-  Update snapshots of ErrorField
> Test: adds component testing for ErrorField and Reset component

- src/lib/components/Form/result/Icon.svelte
- src/lib/components/Form/result/Icon.test.ts
- src/lib/components/Form/result/Json.test.ts
- src/lib/components/Form/result/Result.svelte
- src/lib/components/Form/result/Result.test.ts
- src/lib/components/Form/result/Subtitle.test.ts
- src/lib/components/Form/result/utils.test.ts
- Adds component tests for all components in the section that shows the resulting template
- Fixes a small bug with the copy to clipboard button
> Testing: adds component testing for Result template section

- src/lib/components/Form/template/Subtitle.test.ts
- src/lib/components/Form/template/Template.test.ts
- src/lib/components/Form/template/TextArea.test.ts
- Adds component testing for the template section: Subtitle, Template and TextArea
> Adds testing for the template input section

- src/lib/components/Form/fields/Add.test.ts
- src/lib/components/Form/fields/Badge.test.ts
Adds component testing for the following components of the Fields section
- Add.svelte
- Badge.svelte
> Test: adds component testing for add and badge components

- src/lib/components/Form/fields/Fields.test.ts
- Adds component testing for the Fields component, which accumulates all Merge Field modification related components.
> Test: adds testing for the Fields.svelte component

- src/lib/ShotstackEditTemplate/ShotstackEditTemplateService.test.ts
- src/lib/ShotstackEditTemplate/ShotstackEditTemplateService.ts
- src/lib/components/Form/source/Source.svelte
- When a file is selected to be uploaded using the source field input, if the callback failed, the button would be disabled permanently due to being stuck on the 'loading' mode
- Now the result is not important. At the end of the process it will enable again, whether it finishes or it fails.
- Adds testing for this functionality
> Bugfix: upload file button now correctly enables again when callback fails
